from talon import Context

ctx = Context()

ctx.lists["user.vocabulary"] = {
    "wrap fifty three": "Route 53",
    "i am": "IAM",
    "apt gateway": "API Gateway",
    "ghosty": "Ghostty",
    "get habit": "GitHub",
    "nogs": "Node.js",
    "den": "dotenv",
    "dynamo debye": "DynamoDB",
    "route fifty three": "Route 53",
    "apa gateway": "API Gateway",
    "goes to ty": "Ghostty",
    "get him": "GitHub",
    "nodes": "Node.js",
    "pascal case": "PascalCase",
    "get status": "git status",
    "get commit": "git commit",
    "get push origin man": "git push origin main",
    "get poll": "git pull",
    "gets": "git stash",
    "get rebase": "git rebase",
    "get tiff": "git diff",
    "np in stong": "npm install",
    "np run build": "npm run build",
    "np ramdev": "npm run dev",
    "np tax": "npx tsx",
    "web ho candler": "webhook handler",
    "apr gateway": "API Gateway",
    "rout fifty three": "Route 53",
    "amaral": "IAM role",
    "no ja server": "Node.js server",
    "function": "arrow function",
    "ghosty terminal": "Ghostty terminal",
    "pall request": "pull request",
    "am config": "dotenv config",
    "consol log": "console.log()",
    "undefined": "return undefined",
    "np run deploy": "npm run deploy",
    "package jason": "package.json",
    "index ates": "index.ts",
    "promise": "promise chain",
    "chest test": "jest test",
    "change max": "chmod +x",
    "to grip": "pipe to grep",
    "export deep dwelt": "export default",
    "module": "module.exports",
}
